# Generated by Django 2.2.14 on 2020-07-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_jhgjhg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjhg',
        ),
    ]
